default["prometheus"]["cms"]["db_host"] = "localhost"
default["prometheus"]["cms"]["db_name"] = "cms"
default["prometheus"]["cms"]["db_port"] = "3306"
default["prometheus"]["cms"]["db_user"] = "root"
default["prometheus"]["cms"]["db_pass"] = ""
default["prometheus"]["cms"]["db_driver"] = "mysql"
default["prometheus"]["cms"]["db_prefix"] = ""
