name             'prometheus'
maintainer       'Spiralworks'
maintainer_email 'devops@spiralwks.com'
license          'All rights reserved'
description      'Installs/Configures PrometheusAPI'
version          '0.1.0'

depends 'nginx'
depends 'hhvm'
depends 'composer'
depends 'php5-fpm'
depends 'capistrano'
