---
driver:
  name: vagrant
  customize:
    memory: 512

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[graphite::default]
      - recipe[graphite::graphite_carbon]
      - recipe[graphite::graphite_web]
    attributes:
