---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: centos-7.0
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[consul::default]
    attributes:
      consul:
        datacenter: FortMeade
        bind_interface: eth0
        advertise_interface: eth0
        encrypt: CGXC2NsXW4AvuB4h5ODYzQ==
  - name: source
    run_list:
      - recipe[consul::default]
    attributes:
      consul:
        install_method: source
  - name: packages
    run_list:
      - recipe[consul::default]
    attributes:
      consul:
        datacenter: FortMeade
        bind_interface: eth0
        advertise_interface: eth0
        encrypt: CGXC2NsXW4AvuB4h5ODYzQ==
        install_method: packages
    excludes:
      - centos-7.0
      - centos-6.5
  - name: runit
    run_list:
      - recipe[consul::default]
    attributes:
      consul:
        datacenter: FortMeade
        init_style: runit
  - name: ui
    run_list:
      - recipe[consul::default]
      - recipe[consul::ui]
    attributes:
      consul:
        serve_ui: true
        client_interface: eth0
  - name: cluster
    run_list:
      - recipe[consul::default]
    attributes:
      consul:
        service_mode: cluster
        bootstrap_expect: 1
  - name: atlas
    run_list:
      - recipe[consul::default]
    attributes:
      consul:
        atlas_autojoin: true
        atlas_cluster: <%= ENV.fetch('ATLAS_CLUSTER', 'example/cluster') %>
        atlas_token: <%= ENV.fetch('ATLAS_TOKEN', 'NOT_REAL') %>