name        "opsworks_stack_state_sync"
description "Populates /etc/hosts and /etc/motd"
maintainer  "AWS OpsWorks"
maintainer_email "devops@spiralwks.com"
license     "Apache 2.0"
version     "1.0.0"
